var http = require('http')

var server = http.createServer()

server.on('request', function (req, res) {
  
  // 在服务端发送的数据默认是 utf-8 格式
  // 解决中文乱码: -> 设置头部\
  //   res.writeHeader(200, { 'Content-Type': 'text/html; charset: utf-8' })
  // 浏览器在不知道服务器相应内容的编码情况下, 会按照当前操作系统的默认编码去解析
  // 中文操作系统默认是gbk
  var obj = {
    "status": "success",
    "msg": "调用成功",
    "data": {
      "count": 19,
      "list": [
        {
          "id": 856,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "平台运营9999--互通",
          "sub_title": "",
          "line_no": "44554546546546",
          "pro_no": "d75df432d75260a5733692800e4704ff",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 0,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 4,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 4,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 0,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1587543944,
          "update_time": 1587634276,
          "from_zone": [
            {
              "zone_id": 110107,
              "zone_name": "石景山区"
            }
          ],
          "to_zone": [],
          "plan_date": [
            "2020-04-30",
            "2020-05-29",
            "2020-05-30",
            "2020-05-31",
            "2020-06-29",
            "2020-06-30"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "平台运营9999--互通",
          "is_line_file": 0,
          "picture_path": "http://192.168.9.15:9321/upload/173_1586398943/4067/0/image/gallery/2020-04-09/20040914334910457.jpg",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 54400,
          "market_price_amount": 54400
        },
        {
          "id": 849,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "9321自营--互通",
          "sub_title": "鬼地方鬼地方",
          "line_no": "53454353454311",
          "pro_no": "ef442c898750a3bac252f1fc1c1357a2",
          "scheduling_type": 2,
          "day_num": 2,
          "night_num": 1,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 24,
          "regionalid_3": 76,
          "regionalid_4": 0,
          "from_type": 4,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 4,
          "flag": 1,
          "go_traffic": 2,
          "back_traffic": 1,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 10,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1586836074,
          "update_time": 1587634276,
          "from_zone": [
            {
              "zone_id": 110109,
              "zone_name": "门头沟区"
            },
            {
              "zone_id": 110113,
              "zone_name": "顺义区"
            }
          ],
          "to_zone": [
            {
              "zone_id": 110111,
              "zone_name": "房山区"
            }
          ],
          "plan_date": [
            "2020-04-24",
            "2020-04-25",
            "2020-04-26",
            "2020-04-27",
            "2020-04-28",
            "2020-04-29"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "9321自营--互通",
          "is_line_file": 0,
          "picture_path": "http://192.168.9.15:9321/upload/173_1586398943/4067/0/image/gallery/2020-04-09/20040914335727295.jpg",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 33300,
          "market_price_amount": 33300
        },
        {
          "id": 847,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 260,
          "uid": 9628,
          "title": "直采！！！！",
          "sub_title": "",
          "line_no": "直采！！！！",
          "pro_no": "cc17a6bd8498c80d1e694b06bef3a4e2",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 0,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 0,
          "coupon_amount": 0,
          "view_num": 0,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "快乐派旅游公司,蒙娜丽莎1,,",
          "add_time": 1586426037,
          "update_time": 1586426052,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-04-24",
            "2020-04-25"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "直采！！！！",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "蒙娜丽莎1",
          "uid_mobile": "15659839082",
          "peer_price_amount": 20000,
          "market_price_amount": 20000
        },
        {
          "id": 846,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 260,
          "uid": 9628,
          "title": "平台型",
          "sub_title": "",
          "line_no": "平台型",
          "pro_no": "5e550a113b67b856a69d61f03e6e0023",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 0,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 0,
          "coupon_amount": 0,
          "view_num": 0,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "快乐派旅游公司,蒙娜丽莎1,,",
          "add_time": 1586423682,
          "update_time": 1586425119,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-04-24"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "平台型",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "蒙娜丽莎1",
          "uid_mobile": "15659839082",
          "peer_price_amount": 12300,
          "market_price_amount": 12300
        },
        {
          "id": 845,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 260,
          "uid": 9628,
          "title": "直采型",
          "sub_title": "",
          "line_no": "直采型",
          "pro_no": "8de815e3dd1c60caf879c8975070323e",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 0,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 0,
          "coupon_amount": 0,
          "view_num": 0,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "快乐派旅游公司,蒙娜丽莎1,,",
          "add_time": 1586422819,
          "update_time": 1586422893,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-04-30"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "直采型",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "蒙娜丽莎1",
          "uid_mobile": "15659839082",
          "peer_price_amount": 11100,
          "market_price_amount": 11100
        },
        {
          "id": 842,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "平台运营--互通",
          "sub_title": "",
          "line_no": "445545",
          "pro_no": "4bb4df73258bd5eb9ebf10aaa593355b",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 0,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 4,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 4,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 10,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1586417191,
          "update_time": 1587634276,
          "from_zone": [
            {
              "zone_id": 110107,
              "zone_name": "石景山区"
            }
          ],
          "to_zone": [],
          "plan_date": [
            "2020-04-29",
            "2020-04-29",
            "2020-04-29",
            "2020-04-29",
            "2020-04-29",
            "2020-04-30"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "平台运营--互通",
          "is_line_file": 0,
          "picture_path": "http://192.168.9.15:9321/upload/173_1586398943/4067/0/image/gallery/2020-04-09/20040914334910457.jpg",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 35500,
          "market_price_amount": 35500
        },
        {
          "id": 831,
          "erp_id": 1,
          "company_id": 3506,
          "erp_company_id": 3503,
          "department_id": 248,
          "uid": 9395,
          "title": "测试价格测试价格测试价格测试价格测试价格",
          "sub_title": "测试价格测试价格测试价格",
          "line_no": "qqqqqqqqqq",
          "pro_no": "d27a29d02078229364110d19765f874d",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 24,
          "regionalid_3": 76,
          "regionalid_4": 195,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 2,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 0,
          "coupon_amount": 0,
          "view_num": 1,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "快乐派旅游公司,厦门旅行社勿动,妮妮,156909090901",
          "add_time": 1585294952,
          "update_time": 1585295010,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-04-27",
            "2020-04-28"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "测试价格测试价格测试价格测试价格测试价格",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "蒙娜丽莎",
          "uid_mobile": "15659839000",
          "peer_price_amount": 12100,
          "market_price_amount": 12100
        },
        {
          "id": 825,
          "erp_id": 1,
          "company_id": 3,
          "erp_company_id": 3,
          "department_id": 28,
          "uid": 3,
          "title": "厦门便宜游啦",
          "sub_title": "",
          "line_no": "LeShan20200218",
          "pro_no": "04ad09f7121c9a1b51c46e5879d61c91",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 0,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 2,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 1,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 1,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1582027390,
          "update_time": 1582027390,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-05-19",
            "2020-05-20"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "厦门便宜游啦",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "",
          "uid_name": "大师傅",
          "uid_mobile": "15980777231",
          "peer_price_amount": 20000,
          "market_price_amount": 20000
        },
        {
          "id": 823,
          "erp_id": 1,
          "company_id": 3503,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "标准行程",
          "sub_title": "【严格筛选·销量大拇指】甄品北京·门票全含圆明园通票·黄包车游胡同·24小时接送机",
          "line_no": "K8542433434",
          "pro_no": "369028417939e85a8a7c4a0b2bb8c69c",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 13,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 1,
          "back_traffic": 1,
          "business_type": 1,
          "company_type": 0,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 13,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1578277398,
          "update_time": 1585205500,
          "from_zone": [
            {
              "zone_id": 2147483647,
              "zone_name": "南山滑雪场"
            }
          ],
          "to_zone": [
            {
              "zone_id": 11010050005,
              "zone_name": "云居寺·石经山"
            },
            {
              "zone_id": 11010050008,
              "zone_name": "白龙潭皇家森林公园"
            }
          ],
          "plan_date": [
            "2020-04-30",
            "2020-05-29",
            "2020-05-30",
            "2020-06-29",
            "2020-06-30"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "标准行程",
          "is_line_file": 1,
          "picture_path": "/upload/1/3503/0/image/gallery/2018-09-20/18092011392304995.png",
          "label": [
            {
              "label_id": 43,
              "label_name": "自由行"
            },
            {
              "label_id": 47,
              "label_name": "夕阳红"
            },
            {
              "label_id": 16,
              "label_name": "拉的积分"
            },
            {
              "label_id": 46,
              "label_name": "夕阳红"
            }
          ],
          "owner_user_info": "",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 22200,
          "market_price_amount": 22200
        },
        {
          "id": 819,
          "erp_id": 1,
          "company_id": 3,
          "erp_company_id": 3,
          "department_id": 28,
          "uid": 3,
          "title": "lbc-DJ测试产品（大师傅家的地接产品-测试跨采）",
          "sub_title": "",
          "line_no": "DJkc001",
          "pro_no": "e314b3b4f4c30c5c28ec893f4da84ab4",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 53,
          "regionalid_3": 95,
          "regionalid_4": 250,
          "from_type": 1,
          "line_side_type": 2,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 1,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 5,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1576720834,
          "update_time": 1576720834,
          "from_zone": [],
          "to_zone": [
            {
              "zone_id": 110107,
              "zone_name": "石景山区"
            },
            {
              "zone_id": 110108,
              "zone_name": "海淀区"
            }
          ],
          "plan_date": [
            "2020-04-25",
            "2020-04-26",
            "2020-05-01",
            "2020-05-02",
            "2020-05-03",
            "2020-05-08"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "lbc-DJ测试产品（大师傅家的地接产品-测试跨采）",
          "is_line_file": 1,
          "picture_path": "",
          "label": [],
          "owner_user_info": "",
          "uid_name": "大师傅",
          "uid_mobile": "15980777231",
          "peer_price_amount": 40000,
          "market_price_amount": 40000
        },
        {
          "id": 789,
          "erp_id": 1,
          "company_id": 103,
          "erp_company_id": 103,
          "department_id": 10,
          "uid": 86,
          "title": "云南家的地接产品-lbc",
          "sub_title": "",
          "line_no": "",
          "pro_no": "7574633f6515b46b4a732a77e63367e2",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 53,
          "regionalid_3": 95,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 2,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 1,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 0,
          "coupon_amount": 0,
          "view_num": 6,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1569204175,
          "update_time": 1569204175,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-05-01",
            "2020-05-02",
            "2020-05-03",
            "2020-05-04",
            "2020-05-05",
            "2020-05-06"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "云南家的地接产品-lbc",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "",
          "uid_name": "云南旅游",
          "uid_mobile": "18090078909",
          "peer_price_amount": 30000,
          "market_price_amount": 30000
        },
        {
          "id": 788,
          "erp_id": 1,
          "company_id": 103,
          "erp_company_id": 103,
          "department_id": 10,
          "uid": 86,
          "title": "lbc-云南公司提供的自营产品0002",
          "sub_title": "【希尔顿海景 赠帆船出海】",
          "line_no": "lbcxl001",
          "pro_no": "19b859373a890166573f8ebe370be653",
          "scheduling_type": 1,
          "day_num": 3,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 30,
          "regionalid_3": 214,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 2,
          "back_traffic": 3,
          "business_type": 1,
          "company_type": 0,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 6,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1568958126,
          "update_time": 1574317410,
          "from_zone": [
            {
              "zone_id": 910100,
              "zone_name": "韩国"
            },
            {
              "zone_id": 910200,
              "zone_name": "菲律宾"
            },
            {
              "zone_id": 910302,
              "zone_name": "长崎"
            },
            {
              "zone_id": 910600,
              "zone_name": "马来西亚"
            },
            {
              "zone_id": 910601,
              "zone_name": "兰卡威"
            }
          ],
          "to_zone": [
            {
              "zone_id": 910307,
              "zone_name": "东京"
            }
          ],
          "plan_date": [
            "2020-05-01",
            "2020-05-02",
            "2020-05-03",
            "2020-05-04",
            "2020-05-05",
            "2020-05-06"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "lbc-云南公司提供的自营产品0002",
          "is_line_file": 0,
          "picture_path": "/upload/1/103/0/image/gallery/2018-07-02/18070214192335.jpg",
          "label": [
            {
              "label_id": 7,
              "label_name": "韩国游"
            },
            {
              "label_id": 8,
              "label_name": "B类产品"
            },
            {
              "label_id": 13,
              "label_name": "C类产品"
            },
            {
              "label_id": 14,
              "label_name": "自由行"
            },
            {
              "label_id": 15,
              "label_name": "A类产品"
            },
            {
              "label_id": 16,
              "label_name": "拉的积分"
            },
            {
              "label_id": 18,
              "label_name": "特价-跟团游"
            },
            {
              "label_id": 25,
              "label_name": "我是跟团游标签"
            },
            {
              "label_id": 33,
              "label_name": "品类标签1"
            },
            {
              "label_id": 35,
              "label_name": "夕阳红"
            }
          ],
          "owner_user_info": "",
          "uid_name": "云南旅游",
          "uid_mobile": "18090078909",
          "peer_price_amount": 30000,
          "market_price_amount": 30000
        },
        {
          "id": 758,
          "erp_id": 1,
          "company_id": 3503,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "台湾2日游",
          "sub_title": "",
          "line_no": "K201803243434",
          "pro_no": "6d90322508eba8993b1f349002b8da23",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 207,
          "regionalid_3": 208,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 1,
          "back_traffic": 1,
          "business_type": 1,
          "company_type": 0,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 0,
          "coupon_amount": 0,
          "view_num": 19,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1564366051,
          "update_time": 1587436011,
          "from_zone": [
            {
              "zone_id": 2147483647,
              "zone_name": "南山滑雪场"
            }
          ],
          "to_zone": [
            {
              "zone_id": 2147483647,
              "zone_name": "南山滑雪场"
            }
          ],
          "plan_date": [
            "2020-04-24",
            "2020-04-27",
            "2020-04-29",
            "2020-04-30",
            "2020-05-28",
            "2020-05-29"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "台湾2日游",
          "is_line_file": 1,
          "picture_path": "/upload/1/3503/0/image/gallery/2018-09-20/18092011563815431.jpg",
          "label": [
            {
              "label_id": 43,
              "label_name": "自由行"
            },
            {
              "label_id": 47,
              "label_name": "夕阳红"
            },
            {
              "label_id": 16,
              "label_name": "拉的积分"
            },
            {
              "label_id": 46,
              "label_name": "夕阳红"
            }
          ],
          "owner_user_info": "",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 20000,
          "market_price_amount": 20000
        },
        {
          "id": 727,
          "erp_id": 1,
          "company_id": 3503,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "测试黄河保险",
          "sub_title": "【严格筛选·销量大拇指】甄品北京·门票全含圆明园通票·黄包车游胡同·24小时接送机",
          "line_no": "K8546546546",
          "pro_no": "f7010a47def4f7e54b0e5a07c31e35a6",
          "scheduling_type": 2,
          "day_num": 5,
          "night_num": 4,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 13,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 1,
          "back_traffic": 1,
          "business_type": 1,
          "company_type": 0,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 108,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1560757920,
          "update_time": 1574126656,
          "from_zone": [
            {
              "zone_id": 2147483647,
              "zone_name": "南山滑雪场"
            }
          ],
          "to_zone": [
            {
              "zone_id": 11010050005,
              "zone_name": "云居寺·石经山"
            },
            {
              "zone_id": 11010050008,
              "zone_name": "白龙潭皇家森林公园"
            }
          ],
          "plan_date": [
            "2020-04-28",
            "2020-04-29",
            "2020-04-30"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "测试黄河保险",
          "is_line_file": 1,
          "picture_path": "/upload/1/3503/0/image/gallery/2018-09-20/18092011392304995.png",
          "label": [
            {
              "label_id": 43,
              "label_name": "自由行"
            },
            {
              "label_id": 47,
              "label_name": "夕阳红"
            },
            {
              "label_id": 16,
              "label_name": "拉的积分"
            },
            {
              "label_id": 46,
              "label_name": "夕阳红"
            }
          ],
          "owner_user_info": "",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 179900,
          "market_price_amount": 179900
        },
        {
          "id": 646,
          "erp_id": 1,
          "company_id": 2178,
          "erp_company_id": 3,
          "department_id": 0,
          "uid": 8703,
          "title": "huasontest1",
          "sub_title": "ss",
          "line_no": "112233445566",
          "pro_no": "d1436f0e30071029309264e57fe23880",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 24,
          "regionalid_3": 77,
          "regionalid_4": 0,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 0,
          "coupon_amount": 20,
          "view_num": 16,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "欣欣旅游ERP(huason 哈哈 1212)",
          "add_time": 1548141711,
          "update_time": 1577159000,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-05-01",
            "2020-05-02",
            "2020-05-03",
            "2020-05-04",
            "2020-05-05",
            "2020-05-06"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "huasontest1",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "大师傅 | 15980777231",
          "uid_name": "huason_test",
          "uid_mobile": "13666996633",
          "peer_price_amount": 5000,
          "market_price_amount": 5000
        },
        {
          "id": 589,
          "erp_id": 1,
          "company_id": 3610,
          "erp_company_id": 3503,
          "department_id": 260,
          "uid": 9628,
          "title": "蒙娜丽莎1产品",
          "sub_title": "",
          "line_no": "111",
          "pro_no": "5521e06370f0fee5541b49a60a7791e8",
          "scheduling_type": 1,
          "day_num": 1,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 53,
          "regionalid_3": 0,
          "regionalid_4": 0,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 2,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 0,
          "group_share_flag": 1,
          "coupon_amount": 10000,
          "view_num": 47,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1543917233,
          "update_time": 1583916337,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-04-30"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "蒙娜丽莎1产品",
          "is_line_file": 1,
          "picture_path": "/upload/1/3503/0/image/gallery/2018-11-19/18111917012731633.jpg",
          "label": [
            {
              "label_id": 24,
              "label_name": "我是全局标签"
            }
          ],
          "owner_user_info": "快乐派旅游供公司 | 15659839082",
          "uid_name": "蒙娜丽莎1",
          "uid_mobile": "15659839082",
          "peer_price_amount": 11100,
          "market_price_amount": 11100
        },
        {
          "id": 561,
          "erp_id": 1,
          "company_id": 3503,
          "erp_company_id": 3503,
          "department_id": 0,
          "uid": 9394,
          "title": "地接产品--勿动",
          "sub_title": "",
          "line_no": "KM2345678907",
          "pro_no": "6c6ce4f3f1d7923b766feb1e18ccf28f",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 13,
          "regionalid_3": 15,
          "regionalid_4": 18,
          "from_type": 1,
          "line_side_type": 2,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 0,
          "back_traffic": 0,
          "business_type": 1,
          "company_type": 0,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 1,
          "coupon_amount": 500,
          "view_num": 36,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1540366906,
          "update_time": 1577175349,
          "from_zone": [
            {
              "zone_id": 4294967295,
              "zone_name": "奥林匹克水上公园"
            },
            {
              "zone_id": 11010050003,
              "zone_name": "南锣鼓巷"
            }
          ],
          "to_zone": [
            {
              "zone_id": 11010050012,
              "zone_name": "大栅栏商业街"
            },
            {
              "zone_id": 11010050013,
              "zone_name": "地坛公园"
            }
          ],
          "plan_date": [
            "2020-04-29",
            "2020-04-30",
            "2020-05-31"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "地接产品--勿动",
          "is_line_file": 1,
          "picture_path": "/upload/1/3503/0/image/gallery/2018-09-20/18092013512143687.jpg",
          "label": [
            {
              "label_id": 24,
              "label_name": "我是全局标签"
            },
            {
              "label_id": 43,
              "label_name": "自由行"
            },
            {
              "label_id": 16,
              "label_name": "拉的积分"
            },
            {
              "label_id": 48,
              "label_name": "周边游"
            }
          ],
          "owner_user_info": "",
          "uid_name": "快乐派旅游供公司",
          "uid_mobile": "15659839082",
          "peer_price_amount": 190000,
          "market_price_amount": 190000
        },
        {
          "id": 409,
          "erp_id": 1,
          "company_id": 2283,
          "erp_company_id": 3,
          "department_id": 228,
          "uid": 8775,
          "title": "lbc-供应商上的产品（08-10）",
          "sub_title": "我是新增的产品（\t云端旅游有限公司-工商银行上海分行-6222024100019519876(银行)\t云端旅游有限公司-工商银行上海分行-6222024100019519876(银行)\t云端旅游有限公司-工商银行上海分行-62220241）",
          "line_no": "LBC-001",
          "pro_no": "0183351f0f40d4b30a5d56e31a7cd6eb",
          "scheduling_type": 2,
          "day_num": 3,
          "night_num": 2,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 24,
          "regionalid_3": 76,
          "regionalid_4": 0,
          "from_type": 2,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 2,
          "flag": 1,
          "go_traffic": 2,
          "back_traffic": 3,
          "business_type": 1,
          "company_type": 2,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 1,
          "coupon_amount": 0,
          "view_num": 50,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "欣欣旅游ERP(测试新增-lbc lbc联系人 15980777444)",
          "add_time": 1533884696,
          "update_time": 1577159000,
          "from_zone": [],
          "to_zone": [],
          "plan_date": [
            "2020-04-24",
            "2020-04-25",
            "2020-04-26",
            "2020-04-27",
            "2020-04-28",
            "2020-04-29"
          ],
          "currency_name": "",
          "symbol": "¥",
          "title_from_type_name": "lbc-供应商上的产品（08-10）",
          "is_line_file": 0,
          "picture_path": "",
          "label": [],
          "owner_user_info": "lba | 15980777333",
          "uid_name": "员工3号供",
          "uid_mobile": "15980777351",
          "peer_price_amount": 20000,
          "market_price_amount": 20000
        },
        {
          "id": 391,
          "erp_id": 1,
          "company_id": 3,
          "erp_company_id": 3,
          "department_id": 28,
          "uid": 3,
          "title": "LBC自营产品--【惠美青甘小环线】兰州•塔尔寺•青海湖•茶卡盐湖•张掖丹霞•嘉峪关城楼•敦煌莫高窟 •月牙泉鸣沙山•双飞一卧7日游",
          "sub_title": "ddd",
          "line_no": "lbc测试",
          "pro_no": "cf3fa7593ff8887546741b1ebe48dcf0",
          "scheduling_type": 1,
          "day_num": 2,
          "night_num": 0,
          "group_regionalid_1": 0,
          "group_regionalid_2": 0,
          "group_regionalid_3": 0,
          "group_regionalid_4": 0,
          "regionalid_1": 1,
          "regionalid_2": 53,
          "regionalid_3": 95,
          "regionalid_4": 0,
          "from_type": 1,
          "line_side_type": 1,
          "line_type": 1,
          "structure_type": 1,
          "publish_from": 1,
          "flag": 1,
          "go_traffic": 1,
          "back_traffic": 2,
          "business_type": 1,
          "company_type": 0,
          "audit_flag": 2,
          "approve_flag": 1,
          "shuttle_site_flag": 1,
          "group_share_flag": 0,
          "coupon_amount": 10,
          "view_num": 103,
          "plan_num": 0,
          "sale_plan_num": 0,
          "supplier_remark": "",
          "add_time": 1533538745,
          "update_time": 1587635436,
          "from_zone": [
            {
              "zone_id": 350100,
              "zone_name": "福州市"
            },
            {
              "zone_id": 350200,
              "zone_name": "厦门市"
            }
          ],
          "to_zone": [
            {
              "zone_id": 350500,
              "zone_name": "泉州市"
            },
            {
              "zone_id": 350600,
              "zone_name": "漳州市"
            }
          ],
          "plan_date": [
            "2020-04-25",
            "2020-04-26"
          ],
          "currency_name": "人民币",
          "symbol": "¥",
          "title_from_type_name": "LBC自营产品--【惠美青甘小环线】兰州•塔尔寺•青海湖•茶卡盐湖•张掖丹霞•嘉峪关城楼•敦煌莫高窟 •月牙泉鸣沙山•双飞一卧7日游",
          "is_line_file": 1,
          "picture_path": "/upload/1/1/0/image/gallery/2018-03-15/18031513210193490.jpg",
          "label": [
            {
              "label_id": 15,
              "label_name": "A类产品"
            },
            {
              "label_id": 43,
              "label_name": "自由行"
            },
            {
              "label_id": 51,
              "label_name": "边境游"
            },
            {
              "label_id": 61,
              "label_name": "夕阳红"
            },
            {
              "label_id": 18,
              "label_name": "特价-跟团游"
            },
            {
              "label_id": 33,
              "label_name": "品类标签1"
            },
            {
              "label_id": 65,
              "label_name": "十一大促"
            },
            {
              "label_id": 66,
              "label_name": "特卖"
            }
          ],
          "owner_user_info": "",
          "uid_name": "大师傅",
          "uid_mobile": "15980777231",
          "peer_price_amount": 30000,
          "market_price_amount": 30000
        }
      ]
    }
  }
  res.setHeader('Content-Type', 'text/html; charset=utf-8')   // html 文本 同时解决中文乱码和标签变成字符串的问题
  res.end(JSON.stringify(obj))
  // res.write(resTxt.toString())
  //   res.end()
  // res.end(JSON.stringify(JSON.stringify(resTxt)))
})

server.listen(8011, function () {
  console.log('服务器创建成功')
})
